aplicativo/urls.py
from django.urls import path
from . import views

app_name = 'aplicativo'
urlpatterns = [
    path('disciplinas/add/', views.create_disciplina, name='add_disciplina'),
    path('disciplinas/', views.DisciplinaListView.as_view(), name='disciplinas'),
    path('usuarios/', views.UsuarioListView.as_view(), name='usuarios'),
    path('perfil/<int:pk>/', views.UsuarioDetailView.as_view(), name='detail_perfil'),
    path('perfil/delete/<int:pk>/', views.UsuarioDeleteView.as_view(), name='delete_perfil'),
    path('aula/create/', views.create_aula, name='create_aula'),
    path('aula/<int:pk>/', views.AulaDetailView.as_view(), name='detail_aula'),
    path('aulas/', views.AulaListView.as_view(), name='aulas'),
    path('aula/<int:aula_id>/feedback/', views.create_feedback, name='feedback'),
    path('pesquisa/', views.filtra_disciplinas, name='pesquisa'),
]

tinnerd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('aplicativo/', include('aplicativo.urls')),
    path("admin/", admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} TINNERD
    </title>
    <link rel="icon" type="image/x-icon" href="/static/logo01.svg">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo01.svg' %}" height="150"> </a>
        <h1><a href="{% url 'index' %}">TINNERD</a></h1>
        <nav id="navegacao-principal">
           <ul>
            {% if user.is_authenticated %}
            <li> Logado com {{ user.nome }} </li>
            <li><a href="{% url 'logout' %}">Log out</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Log in</a></li>
            {% endif %}
            <li><a href="{% url 'about' %}">Sobre</a></li>
            {% if user.is_admin %}
            <li><a href="{% url 'aplicativo:disciplinas' %}">Disciplinas</a></li>
            <li><a href="{% url 'aplicativo:usuarios' %}">Usuários</a></li>
            {% endif %}
            {% if user.is_monitor %}
            <li><a href="{% url 'aplicativo:create_aula' %}">Criar Aula</a></li>
            {% endif %}
            {% if user.is_aluno %}
            <li><a href="{% url 'aplicativo:aulas' %}">Aulas</a></li>
            {% endif %}
           </ul>
       </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2022</small>
        </p>
    </footer>
</body>

</html>