aplicativo/urls.py
from django.urls import path
from . import views

app_name = 'aplicativo'
urlpatterns = [
    path('disciplinas/add/', views.create_disciplina, name='add_disciplina'),
    path('disciplinas/', views.DisciplinaListView.as_view(), name='disciplinas'),
    path('usuarios/', views.UsuarioListView.as_view(), name='usuarios'),
    path('perfil/<int:pk>/', views.UsuarioDetailView.as_view(), name='detail_perfil'),
    path('perfil/delete/<int:pk>/', views.UsuarioDeleteView.as_view(), name='delete_perfil'),
    path('aula/create/', views.create_aula, name='create_aula'),
    path('aula/<int:pk>/', views.AulaDetailView.as_view(), name='detail_aula'),
    path('aulas/', views.AulaListView.as_view(), name='aulas'),
    path('aula/<int:aula_id>/feedback/', views.create_feedback, name='feedback'),
    path('pesquisa/', views.filtra_disciplinas, name='pesquisa'),
]

tinnerd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('aplicativo/', include('aplicativo.urls')),
    path("admin/", admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
]

aplicativo/models.py
from django.db import models
from django import forms
from django.conf import settings
from usuarios.models import Usuario
from django.core.validators import MaxValueValidator, MinValueValidator

class Disciplina(models.Model):
    titulo = models.CharField(max_length=255)
    codigo = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.titulo}'

class Dia(models.Model):
    dia = models.CharField(max_length=20, null=True)

    def __str__(self):
        return f'{self.dia}'

class Aula(models.Model):
    monitor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    disciplina = models.ForeignKey(Disciplina, on_delete=models.CASCADE, default=0)
    dia = models.ForeignKey(Dia, on_delete=models.CASCADE, default=0)
    inicio = models.CharField(max_length=20, default=0)
    fim = models.CharField(max_length=20, default=0)

    def __str__(self):
        return f'{self.disciplina}, {self.dia} ({self.inicio} - {self.fim})'

class Feedback(models.Model):
    autor = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    texto = models.TextField(default=None)
    aula = models.ForeignKey(Aula, on_delete=models.CASCADE, default=0)

    def __str__(self):
        return f'{self.autor.username} - "{self.texto}"'

usuarios/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin


class AdmUsuario(BaseUserManager):
    
    def get_by_natural_key(self, email_):
        return self.get(email=email_)

    def create_user(self, nome, email, nusp, curso, is_aluno, is_monitor, password=None):
        if not email:
            raise ValueError('Users must have an e-mail')

        user = self.model(
            nome=nome,
            email=email,
            nusp=nusp,
            curso=curso,
            is_aluno=is_aluno,
            is_monitor=is_monitor,
        )
        user.set_password(password)
        user.activated=True
        user.save(using=self._db)

        if is_aluno:
            group = Group.objects.get(name='Aluno')
            user.groups.add(group)

        if is_monitor:
            group = Group.objects.get(name='Monitor')
            user.groups.add(group)    

        return user

    def create_superuser(self, nome, email, nusp, curso, is_aluno, is_monitor, password):
        user = self.create_user(email=email, 
                                nome=nome,
                                nusp=nusp,
                                curso=curso,
                                is_aluno=is_aluno,
                                is_monitor=is_monitor,
                                password=password,
                                )
        user.activated= True
        user.is_admin = True
        user.is_aluno = True
        user.is_monitor = True
        user.save(using=self._db)
        return user

class Usuario(AbstractBaseUser, PermissionsMixin):
    nome = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(unique=True)
    nusp = models.IntegerField(null=True, blank=True)
    curso = models.CharField(max_length=255, null=True, blank=True)
    is_admin = models.BooleanField('admin status',default=False)
    is_aluno = models.BooleanField('Aluno?', default=False)
    is_monitor = models.BooleanField('Monitor?', default=False)

    objects = AdmUsuario()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nome', 'nusp', 'curso', 'is_aluno', 'is_monitor']

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_superuser(self):
        return self.is_admin

    def natural_key(self):
        return self.email

    def __str__(self):
        return f'{self.nome}'

aplicativo/forms.py
from django.forms import ModelForm
from .models import Disciplina, Aula, Feedback, Dia


class DisciplinaForm(ModelForm):
    class Meta:
        model = Disciplina
        fields = [
            'titulo',
            'codigo',
        ]
        labels = {
            'titulo': 'Nome da Disciplina',
            'codigo': 'Código da Disciplina',
        }

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = [
            'texto',
        ]
        labels = {
            'texto': 'Comentários',
        }

class AulaForm(ModelForm):
    class Meta:
        model = Aula
        fields = [
            'disciplina',
            'dia',
            'inicio',
            'fim',
        ]
        labels = {
            'disciplina': 'Disciplina',
            'dia': 'Dia da Semana',
            'inicio': 'De:',
            'fim':'Até:',
        }

aplicativo/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.decorators import login_required
from .models import Disciplina, Aula, Feedback
from usuarios.models import Usuario
from .forms import DisciplinaForm, FeedbackForm, AulaForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth import get_user_model


@login_required
def create_disciplina(request):
    if request.method == 'POST':
        disciplina_form = DisciplinaForm(request.POST)
        if disciplina_form.is_valid():
            disciplina = Disciplina(**disciplina_form.cleaned_data)
            disciplina.save()
            return HttpResponseRedirect(
                reverse('aplicativo:disciplinas'))
    else:
        disciplina_form = DisciplinaForm()
    context = {'disciplina_form': disciplina_form}
    return render(request, 'aplicativo/add_disciplina.html', context)

class DisciplinaListView(LoginRequiredMixin, generic.ListView):
    model = Disciplina
    template_name = 'aplicativo/lista_disciplinas.html'

class UsuarioDetailView(LoginRequiredMixin, generic.DetailView):
    model = Usuario
    template_name = "aplicativo/detail_perfil.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class UsuarioListView(LoginRequiredMixin, generic.ListView):
    model = Usuario
    template_name = "aplicativo/lista_usuarios.html"

class UsuarioDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Usuario
    template_name = "aplicativo/delete_usuario.html"
    success_url = reverse_lazy('aplicativo:usuarios')

@login_required
def create_aula(request):
    if request.method == 'POST':
        aula_form = AulaForm(request.POST)
        if aula_form.is_valid():
            aula_monitor = request.user
            aula_disciplina = aula_form.cleaned_data['disciplina']
            aula_dia = aula_form.cleaned_data['dia']
            aula_inicio = aula_form.cleaned_data['inicio']
            aula_fim = aula_form.cleaned_data['fim']
            aula = Aula(monitor = aula_monitor,
                        disciplina = aula_disciplina,
                        dia = aula_dia,
                        inicio = aula_inicio,
                        fim = aula_fim)
            aula.save()
            return HttpResponseRedirect(
                reverse('index'))
    else:
        aula_form = AulaForm()
    context = {'aula_form': aula_form}
    return render(request, 'aplicativo/create_aula.html', context)

class AulaListView(LoginRequiredMixin, generic.ListView):
    model = Aula
    template_name = 'aplicativo/lista_aulas.html'

class AulaDetailView(generic.DetailView):
    model = Aula
    template_name = "aplicativo/detail_aula.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

@login_required
def create_feedback(request, aula_id):
    aula = get_object_or_404(Aula, pk=aula_id)
    if request.method == 'POST':
        feedback_form = FeedbackForm(request.POST)
        if feedback_form.is_valid():
            feedback_autor = request.user
            feedback_texto = feedback_form.cleaned_data['texto']
            feedback = Feedback(autor=feedback_autor,
                            texto=feedback_texto,
                            aula=aula)
            feedback.save()
            return HttpResponseRedirect(
                reverse('aplicativo:detail_aula', args=(aula_id, )))
    else:
        feedback_form = FeedbackForm()
    context = {'feedback_form': feedback_form, 'aula': aula}
    return render(request, 'aplicativo/feedback.html', context)

def filtra_disciplinas(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        aula_list = Aula.objects.filter(disciplina__icontains=search_term)
        context = {"aula_list": aula_list}
    return render(request, 'aplicativo/pesquisa.html', context)

aplicativo/templates/aplicativo/add_disciplina.html
{% extends 'base.html' %}

{% block title %}
Adicionar Disciplina
{% endblock title %}

{% block content %}
<h2>Adicionar Disciplina</h2>

<form method="post">
    {% csrf_token %}
    {{ disciplina_form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %} 

aplicativo/templates/aplicativo/delete_usuario.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'aplicativo:delete_perfil' usuario.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja banir o usuário "{{ usuario.nome }}"?
    </p>
    <button type="submit">Banir</button>
</form>

{% endblock content %}

aplicativo/templates/aplicativo/detail_aula.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ aula.monitor }} , {{ aula.disciplina }}</h2>

<section class="dados-de-aula">
    <ul>
        <h4> Dia da semana: </h4>
        <p> {{ aula.dia }} </p>
        <h4> Horário: </h4>
        <p> De {{ aula.inicio }} até {{ aula.fim }} </p>
    </ul>
</section>

<section>
    <header>
        <h5>Feedbacks</h5>
    </header>
    <ul>
        {% if aula.feedback_set.all %}
        {% for feedback in aula.feedback_set.all %}
        <figure>
            <blockquote>
                "{{ feedback.texto }}"
            </blockquote>
            <figcaption>—{{ feedback.autor }}
        </figure>
        {% endfor %}
        {% else %}
        <p>Ainda não existe nenhum feedback para esta aula.</p>
        {% endif %}
    </ul>

    <hr>

    {% if user.is_aluno %}
    <a href="{% url 'aplicativo:feedback' aula.pk %}"><button>Avaliar Monitoria</button></a>
    {% endif %}
</section>

{% endblock content %}

aplicativo/templates/aplicativo/detail_grupo.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ grupo.aula.monitor }} , {{ grupo.aula.disciplina }}</h2>

<section class="dados-de-aula">
    <ul>
        <h4> Dia da semana: </h4>
        <p> {{ grupo.aula.dia }} </p>
        <h4> Horário: </h4>
        <p> De {{ grupo.aula.inicio }} até {{ grupo.aula.fim }} </p>

        {% for usuario in list.alunos.all %}
            <div>
                <p>{{ usuario.name }}</p>
            </div>
        {% endfor %}
    </ul>
</section>

<a href="{% url 'aplicativo:create-feedback' %}"><button>Crie sua Categoria</button></a>

{% endblock content %}

aplicativo/templates/aplicativo/detail_perfil.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ usuario.nome }}</h2>

<section class="dados-de-usuario">
    <ul>
        <li>E-mail: {{ usuario.email }} </li>
        <li>Número USP: {{ usuario.nusp }} </li>
        <li>Curso: {{ usuario.curso }} </li>
    </ul>
    <a href="{% url 'aplicativo:delete_perfil' usuario.id %}"><button>Banir Usuário</button></a>
</section>

{% endblock content %}

aplicativo/templates/aplicativo/feedback.html
{% extends 'base.html' %}

{% block content %}
<h2>Feedback</h2>

<form action="{% url 'aplicativo:feedback' aula.pk %}" method="post">
    {% csrf_token %}
    {{ feedback_form.as_p }}
    <button type="submit">Postar Feedback</button>
</form>

<a href="{% url 'aplicativo:detail_aula' aula.pk %}"><button>Voltar</button></a>
{% endblock content %}

aplicativo/templates/aplicativo/lista_aulas.html
{% extends 'base.html' %}

{% block title %}
Monitorias | 
{% endblock title %}

{% block content %}
<h2>Monitorias disponíveis</h2>

<section>
    <p>Gostaria de ums disciplina específica? <a href="{% url 'aplicativo:pesquisa' %}">Pesquisar</a></p>
</section>

<section>
    {% for aula in aula_list %}
    <hr>
    <article>
        <header>
            <h4>{{ aula.disciplina }} - {{ aula.monitor }} </h4>
            <p>{{ aula.dia }}, de {{ aula.inicio }} às {{ aula.fim }}</p>
            <a href="{% url 'aplicativo:detail_aula' aula.id %}"><button>Detalhes</button></a>
        </header>
    </article>
    {% endfor %}
</section>

{% endblock content %}

aplicativo/templates/aplicativo/lista_disciplinas.html
{% extends 'base.html' %}

{% block title %}
Disciplinas | 
{% endblock title %}

{% block content %}
<h2>Lista de Disciplinas</h2>

<section>
    {% for disciplina in disciplina_list %}
    <hr>
    <article>
        <header>
            <h4>{{ disciplina.titulo }} ({{ disciplina.codigo }}) </h4>
        </header>
    </article>
    {% endfor %}

    <a href="{% url 'aplicativo:add_disciplina' %}"><button>Adicionar Disciplina</button></a>
</section>

{% endblock content %}

aplicativo/templates/aplicativo/lista_usuarios.html
{% extends 'base.html' %}

{% block title %}
Usuários | 
{% endblock title %}

{% block content %}
<h2>Lista de Usuários</h2>

<section>
    {% for usuario in usuario_list %}
    <hr>
    <article>
        <header>
            <h4><a href="{% url 'aplicativo:detail_perfil' usuario.id %}">{{ usuario.nome }}</a></h4>
        </header>
    </article>
    {% endfor %}
</section>

{% endblock content %}

aplicativo/templates/aplicativo/pesquisa.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'aplicativo:pesquisa' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if aula_list %}
<section class="lista-de-cards">
    {% for aula in aula_list %}
    <article class="card">
        <p>{{ aula.disciplina }} - {{ aula.monitor }} </p>
        <a href="{% url 'aplicativo:detail_aula' aula.id %}"><button>Detalhes</button></a>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}